version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  # postgres:
  #   image: postgres:alpine
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  # go_server_1:
  #   build:
  #     context: .
  #   container_name: go_server_1
  #   environment:
  #     - NODE_ID=1
  #     - REDIS_HOST=redis
  #     - POSTGRES_HOST=postgres
  #     - KAFKA_BROKER=kafka:9092
  #   depends_on:
  #     - redis
  #     - postgres
  #     - kafka
  #   ports:
  #     - "8081:8080"

  # go_server_2:
  #   build:
  #     context: .
  #   container_name: go_server_2
  #   environment:
  #     - NODE_ID=2
  #     - REDIS_HOST=redis
  #     - POSTGRES_HOST=postgres
  #     - KAFKA_BROKER=kafka:9092
  #   depends_on:
  #     - redis
  #     - postgres
  #     - kafka
  #   ports:
  #     - "8082:8080"

volumes:
  postgres_data:
